[phases.setup]
nixPkgs = ["apacheHttpd", "php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mysqli", "php82Extensions.curl", "php82Extensions.mbstring", "php82Extensions.openssl"]

[phases.build]
cmds = [
  "cp nixpacks-apache.conf /etc/apache2/httpd.conf || true"
]

[start]
cmd = "httpd -f /app/nixpacks-apache.conf -DFOREGROUND"
